apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- pv.yaml
- service.yaml
namespace: http-wallpaper
commonLabels:
  app.kubernetes.io/name: http-wallpaper
  app.kubernetes.io/part-of: http-wallpaper
  app.kubernetes.io/version: 1.0.0
