apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-wallpaper-images
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
